import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Header from "@/components/Home/Header/Header";
import Deals from "@/components/Home/Services/Deals";

const inter = Inter({ subsets: ["latin"] });

export const dealPosters = [
  {
    redbus: "/../public/images/next-deals/redbus.bmp",
    // "/../public/images/next-deals/breakout-room.bmp",
    // "/../public/images/next-deals/gocar.bmp",
    // "/../public/images/next-deals/sunwaypals.bmp",
    // "/../public/images/next-deals/windlab.bmp",
    // "/../public/images/next-deals/hauntu.bmp",
    // "/../public/images/next-deals/bus-online-ticket.bmp",
  },
];

const data = [
  {
    title: "Title 1",
    description:
      "Elit irure ullamco sint cillum in cillum excepteur incididunt incididunt Lorem qui.",
    image: dealPosters[0],
  },
  {
    title: "Title 2",
    description:
      "Minim non exercitation incididunt deserunt eiusmod irure amet mollit veniam anim eiusmod deserunt aliqua tempor.",
    image: dealPosters[1],
  },
];

export default function NextDeals() {
  return (
    <>
      <Head>
        <title>NextEvents for you</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title="NextDeals for you" />
      <Deals data={data} />
    </>
  );
}
