import Head from "next/head";
import Header from "@/components/Home/Header/Header";

export default function NextEvents() {
  return (
    <>
      <Head>
        <title>NextEvents for you</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title="Next Events" />
      <div className="container font-bold text-center py-64">Coming soon!</div>
    </>
  );
}
